name: Storybook Build & Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build Storybook
      run: yarn build-storybook
    
    - name: Upload Storybook artifact
      uses: actions/upload-artifact@v4
      with:
        name: storybook-build
        path: storybook-static/
        retention-days: 30
    
    - name: Deploy to GitHub Pages (Storybook)
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
        publish_branch: gh-pages-storybook
        destination_dir: storybook

  test-storybook:
    runs-on: ubuntu-latest
    needs: build-storybook
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Download Storybook artifact
      uses: actions/download-artifact@v4
      with:
        name: storybook-build
        path: storybook-static/
    
    - name: Verify Storybook build
      run: |
        echo "Checking Storybook output..."
        ls -la storybook-static/
        test -f storybook-static/index.html && echo "✅ Storybook built successfully!" || exit 1
