name: Storybook Test Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        yarn install --frozen-lockfile
        echo "Dependencies installed successfully!"
    
    - name: Build Storybook
      run: |
        echo "Building Storybook..."
        yarn build-storybook
        echo "Storybook build complete!"
    
    - name: Verify Storybook build
      run: |
        echo "Verifying Storybook output..."
        ls -la storybook-static/
        echo "Files in storybook-static:"
        find storybook-static -type f
        echo "Checking for index.html..."
        test -f storybook-static/index.html && echo "✅ index.html found!" || echo "❌ index.html missing!"
    
    - name: Upload Storybook artifact
      uses: actions/upload-artifact@v4
      with:
        name: storybook-build
        path: storybook-static/
        retention-days: 7
