name: Storybook Test Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Delete yarn.lock to force fresh resolution
      run: rm -f yarn.lock
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        yarn install
        echo "Dependencies installed successfully!"
    
    - name: Build Storybook
      run: |
        echo "Building Storybook..."
        yarn build-storybook
        echo "Storybook build complete!"
    
    - name: Verify Storybook build
      run: |
        echo "Verifying Storybook output..."
        ls -la storybook-static/
        echo "Files in storybook-static:"
        find storybook-static -type f
        echo "Checking for index.html..."
        test -f storybook-static/index.html && echo "✅ index.html found!" || echo "❌ index.html missing!"
    
    - name: Upload Storybook artifact
      uses: actions/upload-artifact@v4
      with:
        name: storybook-build
        path: storybook-static/
        retention-days: 7

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: build-storybook
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Storybook artifact
      uses: actions/download-artifact@v4
      with:
        name: storybook-build
        path: storybook-static/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
        destination_dir: storybook
        cname: false
